#!/bin/sh

#
# Copyright 2015 the original author or authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

##############################################################################
#
#  Gradle start up script for POSIX generated by Gradle.
#
##############################################################################

# Attempt to set APP_HOME

# Resolve links: $0 may be a link
PRG="$0"
# Need this for relative symlinks.
while [ -h "$PRG" ] ; do
    ls=`ls -ld "$PRG"`
    link=`expr "$ls" : '.*-> \(.*\)$'`
    if expr "$link" : '/.*' > /dev/null; then
        PRG="$link"
    else
        PRG=`dirname "$PRG"`"/$link"
    fi
done
SAVED="`pwd`"
dirname "$PRG" > /dev/null
APP_HOME="`pwd -P`"
cd "$SAVED"

APP_NAME="Gradle"
APP_BASE_NAME=`basename "$0"`

# Add default JVM options here. You can also use JAVA_OPTS and GRADLE_OPTS to pass JVM options to this script.
DEFAULT_JVM_OPTS="-Xmx4096m "

# Use the maximum available, or set MAX_FD != -1 to use that value.
MAX_FD="maximum"

warn () {
    echo "$*"
}

die () {
    echo
    echo "$*"
    echo
    exit 1
}

# OS specific support (must be 'true' or 'false').
cygwin=false
darwin=false
mingw=false
case "`uname`" in
  CYGWIN* )
    cygwin=true
    ;;
  Darwin* )
    darwin=true
    ;;
  MINGW* )
    mingw=true
    ;;
esac

# For Cygwin, ensure paths are in UNIX format before anything is touched.
if $cygwin ; then
    [ -n "$JAVA_HOME" ] && JAVA_HOME=`cygpath --unix "$JAVA_HOME"`
    [ -n "$CLASSPATH" ] && CLASSPATH=`cygpath --path --unix "$CLASSPATH"`
fi

# Attempt to find JAVA_HOME
if [ -z "$JAVA_HOME" ] ; then
    javaExecutable="`which javac`"
    if [ -n "$javaExecutable" ] && ! [ "`expr "$javaExecutable" : '\(.*\)/bin/javac$'`" = '/' ] ; then
        # readlink(1) is not available as standard on Solaris 10.
        readLink=`which readlink`
        if [ ! `expr "$readLink" : '/.*'` = '/' ] ; then
            readLink=`which greadlink`
        fi
        if [ -n "$readLink" ] ; then
            javaExecutable=`readlink -f "$javaExecutable"`
            javaHome=`expr "$javaExecutable" : '\(.*\)/bin/javac$'`
            JAVA_HOME="$javaHome"
            export JAVA_HOME
        fi
    fi
fi

if [ -z "$JAVA_HOME" ] ; then
    warn "JAVA_HOME environment variable is not set."
    warn "We recommend setting this in .bashrc or .bash_profile for your user."
    javaExecutable="`which java`"
else
    javaExecutable="$JAVA_HOME/bin/java"
fi

if [ ! -x "$javaExecutable" ] ; then
    die "Could not find java executable in JAVA_HOME or on PATH."
fi

# Increase the maximum file descriptors if we can.
if [ "$cygwin" = "false" -a "$darwin" = "false" ] ; then
    MAX_FD_LIMIT=`ulimit -H -n`
    if [ $? -eq 0 ] ; then
        if [ "$MAX_FD" = "maximum" -o "$MAX_FD" = "max" ] ; then
            MAX_FD="$MAX_FD_LIMIT"
        fi
        ulimit -n $MAX_FD
        if [ $? -ne 0 ] ; then
            warn "Could not set maximum file descriptor limit: $MAX_FD"
        fi
    fi
fi

# For Darwin, add options to specify how the application appears in the dock
if $darwin; then
    GRADLE_OPTS="$GRADLE_OPTS "
fi

# For Cygwin, switch paths to Windows format before running java
if $cygwin ; then
    APP_HOME=`cygpath --path --windows "$APP_HOME"`
    [ -n "$JAVA_HOME" ] && JAVA_HOME=`cygpath --path --windows "$JAVA_HOME"`
    [ -n "$CLASSPATH" ] && CLASSPATH=`cygpath --path --windows "$CLASSPATH"`
    [ -n "$DEFAULT_JVM_OPTS" ] && DEFAULT_JVM_OPTS=`cygpath --path --windows "$DEFAULT_JVM_OPTS"`
fi

# Collect all arguments for the java command, stacking in reverse order:
#   * args from the command line
#   * the main class name
#   * -classpath
#   * -D...appname settings
#   * --module-path (only if needed)
#   * DEFAULT_JVM_OPTS, JAVA_OPTS, and GRADLE_OPTS
#   * the java executable and any arguments to it

# For Cygwin or MSYS, switch paths to Windows format before running java
if [ "$cygwin" = "true" -o "$mingw" = "true" ] ; then
    APP_HOME=`cygpath --path --windows "$APP_HOME"`
    [ -n "$JAVA_HOME" ] && JAVA_HOME=`cygpath --path --windows "$JAVA_HOME"`
    [ -n "$CLASSPATH" ] && CLASSPATH=`cygpath --path --windows "$CLASSPATH"`
    [ -n "$DEFAULT_JVM_OPTS" ] && DEFAULT_JVM_OPTS=`cygpath --path --windows "$DEFAULT_JVM_OPTS"`
fi

# Collect all arguments for the java command:
args=()
while [ $# -gt 0 ] ; do
    if [ "$1" = "--module-path" ] ; then
        module_path="$2"
        shift 2
    else
        args="${args[@]}" "$1"
        shift 1
    fi
done

# Add module path if needed
if [ -n "$module_path" ] ; then
    args="${args[@]}" "--module-path" "$module_path"
fi

# Add default JVM options.
args="${args[@]}" $DEFAULT_JVM_OPTS
args="${args[@]}" $JAVA_OPTS
args="${args[@]}" $GRADLE_OPTS

# Add main class name.
args="${args[@]}" org.gradle.wrapper.GradleWrapperMain

# Add java executable.
args="$javaExecutable" "${args[@]}"

# Execute the command
"${args[@]}"